"""协议模板库 - 根据不同协议拆分"""
from .modbus_rtu import MODBUS_RTU_TEMPLATES
from .modbus_tcp import MODBUS_TCP_TEMPLATES
from .custom_example import CUSTOM_EXAMPLE_TEMPLATES
from .grms_control import GRMS_CONTROL_TEMPLATES
from .grms_time import GRMS_TIME_TEMPLATES
from .grms_query import GRMS_QUERY_TEMPLATES
from .grms_data import GRMS_DATA_TEMPLATES
from .grms_cert import GRMS_CERT_TEMPLATES
from .grms_room import GRMS_ROOM_TEMPLATES
from .json_examples import JSON_TEMPLATES


# 合并所有预设协议模板
PRESET_TEMPLATES = {}
PRESET_TEMPLATES.update(MODBUS_RTU_TEMPLATES)
PRESET_TEMPLATES.update(MODBUS_TCP_TEMPLATES)
PRESET_TEMPLATES.update(CUSTOM_EXAMPLE_TEMPLATES)

# GRMS 协议族 - 包装在 'GRMS' 协议名下（保持3层结构：协议名→命令名→{fields,desc}）
PRESET_TEMPLATES['GRMS'] = {}
PRESET_TEMPLATES['GRMS'].update(GRMS_CONTROL_TEMPLATES)
PRESET_TEMPLATES['GRMS'].update(GRMS_TIME_TEMPLATES)
PRESET_TEMPLATES['GRMS'].update(GRMS_QUERY_TEMPLATES)
PRESET_TEMPLATES['GRMS'].update(GRMS_DATA_TEMPLATES)
PRESET_TEMPLATES['GRMS'].update(GRMS_CERT_TEMPLATES)
PRESET_TEMPLATES['GRMS'].update(GRMS_ROOM_TEMPLATES)

# JSON 协议
PRESET_TEMPLATES.update(JSON_TEMPLATES)
