"""GRMS 监控协议 - 控制类命令 (0x01-0x08)
控制空调、控制房态、控制通道、控制窗帘
"""

GRMS_CONTROL_TEMPLATES = {
    # ===== 1.2 控制空调 (0x01/0x02) =====
    '控制空调(发送)': {
        'fields': [
            {'name': 'Header', 'hex_value': 'BA', 'byte_count': 1, 'field_type': '固定值', 'description': '命令头'},
            {'name': 'Func', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '功能码 0x01'},
            {'name': 'Sequence', 'hex_value': '0001', 'byte_count': 2, 'field_type': '数据', 'description': '流水号'},
            {'name': 'Box', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备地址'},
            {'name': 'TotalLen', 'hex_value': '', 'byte_count': 2, 'field_type': '长度', 'description': '命令长度之和', 'length_start': 0, 'length_end': 3, 'length_byte_order': 'big'},
            {'name': 'DeviceCode', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备编码'},
            {'name': 'DeviceBox', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备地址'},
            {'name': 'ControlDataLen', 'hex_value': '0009', 'byte_count': 2, 'field_type': '数据', 'description': '控制数据长度'},
            {'name': '空调ID', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '空调ID [1-255]'},
            {'name': '开关', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '0=关, 1=开, 255=默认', 'parse_mode': '枚举映射', 'enum_mappings': [{'value': 0, 'label': '关'}, {'value': 1, 'label': '开'}, {'value': 255, 'label': '默认'}]},
            {'name': '风速', 'hex_value': '64', 'byte_count': 1, 'field_type': '数据', 'description': '0=关, 1-100=档位, 104=自动, 255=默认'},
            {'name': '模式', 'hex_value': '02', 'byte_count': 1, 'field_type': '数据', 'description': '0=关, 1=通风, 2=制冷, 3=制热, 5=除湿, 6=自动, 255=默认', 'parse_mode': '枚举映射', 'enum_mappings': [{'value': 0, 'label': '关'}, {'value': 1, 'label': '通风'}, {'value': 2, 'label': '制冷'}, {'value': 3, 'label': '制热'}, {'value': 5, 'label': '除湿'}, {'value': 6, 'label': '自动'}, {'value': 255, 'label': '默认'}]},
            {'name': '设置温度', 'hex_value': '00C8', 'byte_count': 2, 'field_type': '数据', 'description': '[-99°C,99°C] 精度0.1°C, bit15=符号, bit14-0=数值'},
            {'name': '预留1', 'hex_value': '00', 'byte_count': 1, 'field_type': '数据', 'description': '预留'},
            {'name': '预留2', 'hex_value': '00', 'byte_count': 1, 'field_type': '数据', 'description': '预留'},
            {'name': '预留3', 'hex_value': '00', 'byte_count': 1, 'field_type': '数据', 'description': '预留'},
            {'name': 'CRC16', 'hex_value': '', 'byte_count': 2, 'field_type': '校验', 'description': 'CRC16校验(高位在前)', 'checksum_algorithm': 'CRC16/MODBUS', 'checksum_start': 0, 'checksum_end': 15, 'checksum_byte_order': 'big'},
        ],
        'desc': 'GRMS控制空调(发送)',
    },
    '控制空调(回复)': {
        'fields': [
            {'name': 'Header', 'hex_value': 'BA', 'byte_count': 1, 'field_type': '固定值', 'description': '命令头'},
            {'name': 'Func', 'hex_value': '02', 'byte_count': 1, 'field_type': '数据', 'description': '功能码 0x02'},
            {'name': 'Sequence', 'hex_value': '0001', 'byte_count': 2, 'field_type': '数据', 'description': '流水号'},
            {'name': 'Box', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备地址'},
            {'name': 'TotalLen', 'hex_value': '', 'byte_count': 2, 'field_type': '长度', 'description': '命令长度之和', 'length_start': 0, 'length_end': 3, 'length_byte_order': 'big'},
            {'name': 'DeviceCode', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备编码'},
            {'name': 'DeviceBox', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备地址'},
            {'name': 'Result', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '0=失败, 1=成功', 'parse_mode': '枚举映射', 'enum_mappings': [{'value': 0, 'label': '失败'}, {'value': 1, 'label': '成功'}]},
            {'name': 'CRC16', 'hex_value': '', 'byte_count': 2, 'field_type': '校验', 'description': 'CRC16校验(高位在前)', 'checksum_algorithm': 'CRC16/MODBUS', 'checksum_start': 0, 'checksum_end': 7, 'checksum_byte_order': 'big'},
        ],
        'desc': 'GRMS控制空调(回复)',
    },
    # ===== 1.3 控制房态 (0x03/0x04) =====
    '控制房态(发送)': {
        'fields': [
            {'name': 'Header', 'hex_value': 'BA', 'byte_count': 1, 'field_type': '固定值', 'description': '命令头'},
            {'name': 'Func', 'hex_value': '03', 'byte_count': 1, 'field_type': '数据', 'description': '功能码 0x03'},
            {'name': 'Sequence', 'hex_value': '0001', 'byte_count': 2, 'field_type': '数据', 'description': '流水号'},
            {'name': 'Box', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备地址'},
            {'name': 'TotalLen', 'hex_value': '', 'byte_count': 2, 'field_type': '长度', 'description': '命令长度之和', 'length_start': 0, 'length_end': 3, 'length_byte_order': 'big'},
            {'name': 'DeviceCode', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备编码'},
            {'name': 'DeviceBox', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备地址'},
            {'name': 'RoomState', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '0=待租, 1=已租, 2=预定', 'parse_mode': '枚举映射', 'enum_mappings': [{'value': 0, 'label': '待租'}, {'value': 1, 'label': '已租'}, {'value': 2, 'label': '预定'}]},
            {'name': 'CRC16', 'hex_value': '', 'byte_count': 2, 'field_type': '校验', 'description': 'CRC16校验(高位在前)', 'checksum_algorithm': 'CRC16/MODBUS', 'checksum_start': 0, 'checksum_end': 7, 'checksum_byte_order': 'big'},
        ],
        'desc': 'GRMS控制房态(发送)',
    },
    '控制房态(回复)': {
        'fields': [
            {'name': 'Header', 'hex_value': 'BA', 'byte_count': 1, 'field_type': '固定值', 'description': '命令头'},
            {'name': 'Func', 'hex_value': '04', 'byte_count': 1, 'field_type': '数据', 'description': '功能码 0x04'},
            {'name': 'Sequence', 'hex_value': '0001', 'byte_count': 2, 'field_type': '数据', 'description': '流水号'},
            {'name': 'Box', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备地址'},
            {'name': 'TotalLen', 'hex_value': '', 'byte_count': 2, 'field_type': '长度', 'description': '命令长度之和', 'length_start': 0, 'length_end': 3, 'length_byte_order': 'big'},
            {'name': 'DeviceCode', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备编码'},
            {'name': 'DeviceBox', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备地址'},
            {'name': 'Result', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '0=失败, 1=成功', 'parse_mode': '枚举映射', 'enum_mappings': [{'value': 0, 'label': '失败'}, {'value': 1, 'label': '成功'}]},
            {'name': 'CRC16', 'hex_value': '', 'byte_count': 2, 'field_type': '校验', 'description': 'CRC16校验(高位在前)', 'checksum_algorithm': 'CRC16/MODBUS', 'checksum_start': 0, 'checksum_end': 7, 'checksum_byte_order': 'big'},
        ],
        'desc': 'GRMS控制房态(回复)',
    },
    # ===== 1.4 控制通道 (0x05/0x06) =====
    '控制通道(发送)': {
        'fields': [
            {'name': 'Header', 'hex_value': 'BA', 'byte_count': 1, 'field_type': '固定值', 'description': '命令头'},
            {'name': 'Func', 'hex_value': '05', 'byte_count': 1, 'field_type': '数据', 'description': '功能码 0x05'},
            {'name': 'Sequence', 'hex_value': '0001', 'byte_count': 2, 'field_type': '数据', 'description': '流水号'},
            {'name': 'Box', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备地址'},
            {'name': 'TotalLen', 'hex_value': '', 'byte_count': 2, 'field_type': '长度', 'description': '命令长度之和', 'length_start': 0, 'length_end': 3, 'length_byte_order': 'big'},
            {'name': 'DeviceCode', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备编码'},
            {'name': 'DeviceBox', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备地址'},
            {'name': 'ControlDataLen', 'hex_value': '0008', 'byte_count': 2, 'field_type': '数据', 'description': '控制数据长度'},
            {'name': '通道号', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '通道号 [1-255]'},
            {'name': '通道类型', 'hex_value': '00', 'byte_count': 1, 'field_type': '数据', 'description': '0=开关, 1=调光, 2=LED', 'parse_mode': '枚举映射', 'enum_mappings': [{'value': 0, 'label': '开关'}, {'value': 1, 'label': '调光'}, {'value': 2, 'label': 'LED'}]},
            {'name': '亮度Level', 'hex_value': '64', 'byte_count': 1, 'field_type': '数据', 'description': '[0-100]'},
            {'name': '渐变时间', 'hex_value': '0064', 'byte_count': 2, 'field_type': '数据', 'description': '单位:毫秒'},
            {'name': '预留1', 'hex_value': '00', 'byte_count': 1, 'field_type': '数据', 'description': '预留'},
            {'name': '预留2', 'hex_value': '00', 'byte_count': 1, 'field_type': '数据', 'description': '预留'},
            {'name': '预留3', 'hex_value': '00', 'byte_count': 1, 'field_type': '数据', 'description': '预留'},
            {'name': 'CRC16', 'hex_value': '', 'byte_count': 2, 'field_type': '校验', 'description': 'CRC16校验(高位在前)', 'checksum_algorithm': 'CRC16/MODBUS', 'checksum_start': 0, 'checksum_end': 14, 'checksum_byte_order': 'big'},
        ],
        'desc': 'GRMS控制通道(发送)',
    },
    '控制通道(回复)': {
        'fields': [
            {'name': 'Header', 'hex_value': 'BA', 'byte_count': 1, 'field_type': '固定值', 'description': '命令头'},
            {'name': 'Func', 'hex_value': '06', 'byte_count': 1, 'field_type': '数据', 'description': '功能码 0x06'},
            {'name': 'Sequence', 'hex_value': '0001', 'byte_count': 2, 'field_type': '数据', 'description': '流水号'},
            {'name': 'Box', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备地址'},
            {'name': 'TotalLen', 'hex_value': '', 'byte_count': 2, 'field_type': '长度', 'description': '命令长度之和', 'length_start': 0, 'length_end': 3, 'length_byte_order': 'big'},
            {'name': 'DeviceCode', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备编码'},
            {'name': 'DeviceBox', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备地址'},
            {'name': 'Result', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '0=失败, 1=成功', 'parse_mode': '枚举映射', 'enum_mappings': [{'value': 0, 'label': '失败'}, {'value': 1, 'label': '成功'}]},
            {'name': 'CRC16', 'hex_value': '', 'byte_count': 2, 'field_type': '校验', 'description': 'CRC16校验(高位在前)', 'checksum_algorithm': 'CRC16/MODBUS', 'checksum_start': 0, 'checksum_end': 7, 'checksum_byte_order': 'big'},
        ],
        'desc': 'GRMS控制通道(回复)',
    },
    # ===== 1.5 控制窗帘 (0x07/0x08) =====
    '控制窗帘(发送)': {
        'fields': [
            {'name': 'Header', 'hex_value': 'BA', 'byte_count': 1, 'field_type': '固定值', 'description': '命令头'},
            {'name': 'Func', 'hex_value': '07', 'byte_count': 1, 'field_type': '数据', 'description': '功能码 0x07'},
            {'name': 'Sequence', 'hex_value': '0001', 'byte_count': 2, 'field_type': '数据', 'description': '流水号'},
            {'name': 'Box', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备地址'},
            {'name': 'TotalLen', 'hex_value': '', 'byte_count': 2, 'field_type': '长度', 'description': '命令长度之和', 'length_start': 0, 'length_end': 3, 'length_byte_order': 'big'},
            {'name': 'DeviceCode', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备编码'},
            {'name': 'DeviceBox', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备地址'},
            {'name': 'ControlDataLen', 'hex_value': '0007', 'byte_count': 2, 'field_type': '数据', 'description': '控制数据长度'},
            {'name': '窗帘编号', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '窗帘编号 [1-255]'},
            {'name': '窗帘状态', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '0=关, 1=开, 2=停', 'parse_mode': '枚举映射', 'enum_mappings': [{'value': 0, 'label': '关'}, {'value': 1, 'label': '开'}, {'value': 2, 'label': '停'}]},
            {'name': '预留1', 'hex_value': '00', 'byte_count': 1, 'field_type': '数据', 'description': '预留'},
            {'name': '预留2', 'hex_value': '00', 'byte_count': 1, 'field_type': '数据', 'description': '预留'},
            {'name': '预留3', 'hex_value': '00', 'byte_count': 1, 'field_type': '数据', 'description': '预留'},
            {'name': '预留4', 'hex_value': '00', 'byte_count': 1, 'field_type': '数据', 'description': '预留'},
            {'name': '预留5', 'hex_value': '00', 'byte_count': 1, 'field_type': '数据', 'description': '预留'},
            {'name': 'CRC16', 'hex_value': '', 'byte_count': 2, 'field_type': '校验', 'description': 'CRC16校验(高位在前)', 'checksum_algorithm': 'CRC16/MODBUS', 'checksum_start': 0, 'checksum_end': 14, 'checksum_byte_order': 'big'},
        ],
        'desc': 'GRMS控制窗帘(发送)',
    },
    '控制窗帘(回复)': {
        'fields': [
            {'name': 'Header', 'hex_value': 'BA', 'byte_count': 1, 'field_type': '固定值', 'description': '命令头'},
            {'name': 'Func', 'hex_value': '08', 'byte_count': 1, 'field_type': '数据', 'description': '功能码 0x08'},
            {'name': 'Sequence', 'hex_value': '0001', 'byte_count': 2, 'field_type': '数据', 'description': '流水号'},
            {'name': 'Box', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备地址'},
            {'name': 'TotalLen', 'hex_value': '', 'byte_count': 2, 'field_type': '长度', 'description': '命令长度之和', 'length_start': 0, 'length_end': 3, 'length_byte_order': 'big'},
            {'name': 'DeviceCode', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备编码'},
            {'name': 'DeviceBox', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备地址'},
            {'name': 'Result', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '0=失败, 1=成功', 'parse_mode': '枚举映射', 'enum_mappings': [{'value': 0, 'label': '失败'}, {'value': 1, 'label': '成功'}]},
            {'name': 'CRC16', 'hex_value': '', 'byte_count': 2, 'field_type': '校验', 'description': 'CRC16校验(高位在前)', 'checksum_algorithm': 'CRC16/MODBUS', 'checksum_start': 0, 'checksum_end': 7, 'checksum_byte_order': 'big'},
        ],
        'desc': 'GRMS控制窗帘(回复)',
    },
}
