"""GRMS 监控协议 - 查询类命令 (0x11-0x1E)
查询空调、查询房务、查询房态、查询通道、查询窗帘、查询日期时间、查询调试授权
"""

GRMS_QUERY_TEMPLATES = {
    # ===== 1.9 查询空调 (0x11/0x12) =====
    '查询空调(发送)': {
        'fields': [
            {'name': 'Header', 'hex_value': 'BA', 'byte_count': 1, 'field_type': '固定值', 'description': '命令头'},
            {'name': 'Func', 'hex_value': '11', 'byte_count': 1, 'field_type': '数据', 'description': '功能码 0x11'},
            {'name': 'Sequence', 'hex_value': '0001', 'byte_count': 2, 'field_type': '数据', 'description': '流水号'},
            {'name': 'Box', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备地址'},
            {'name': 'TotalLen', 'hex_value': '', 'byte_count': 2, 'field_type': '长度', 'description': '命令长度之和', 'length_start': 0, 'length_end': 3, 'length_byte_order': 'big'},
            {'name': 'DeviceCode', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备编码'},
            {'name': 'DeviceBox', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备地址'},
            {'name': 'QueryDataLen', 'hex_value': '0001', 'byte_count': 2, 'field_type': '数据', 'description': '查询数据长度'},
            {'name': '空调ID', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '空调ID [1-255]'},
            {'name': 'CRC16', 'hex_value': '', 'byte_count': 2, 'field_type': '校验', 'description': 'CRC16校验(高位在前)', 'checksum_algorithm': 'CRC16/MODBUS', 'checksum_start': 0, 'checksum_end': 8, 'checksum_byte_order': 'big'},
        ],
        'desc': 'GRMS查询空调(发送)',
    },
    '查询空调(回复)': {
        'fields': [
            {'name': 'Header', 'hex_value': 'BA', 'byte_count': 1, 'field_type': '固定值', 'description': '命令头'},
            {'name': 'Func', 'hex_value': '12', 'byte_count': 1, 'field_type': '数据', 'description': '功能码 0x12'},
            {'name': 'Sequence', 'hex_value': '0001', 'byte_count': 2, 'field_type': '数据', 'description': '流水号'},
            {'name': 'Box', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备地址'},
            {'name': 'TotalLen', 'hex_value': '', 'byte_count': 2, 'field_type': '长度', 'description': '命令长度之和', 'length_start': 0, 'length_end': 3, 'length_byte_order': 'big'},
            {'name': 'DeviceCode', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备编码'},
            {'name': 'DeviceBox', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备地址'},
            {'name': 'ResponseDataLen', 'hex_value': '000D', 'byte_count': 2, 'field_type': '数据', 'description': '应答数据长度'},
            {'name': '空调ID', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '空调ID [1-255]'},
            {'name': '开关', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '0=关, 1=开, 255=默认', 'parse_mode': '枚举映射', 'enum_mappings': [{'value': 0, 'label': '关'}, {'value': 1, 'label': '开'}, {'value': 255, 'label': '默认'}]},
            {'name': '风速', 'hex_value': '64', 'byte_count': 1, 'field_type': '数据', 'description': '0=关, 1-100=档位, 104=自动, 255=默认'},
            {'name': '模式', 'hex_value': '02', 'byte_count': 1, 'field_type': '数据', 'description': '0=关, 1=通风, 2=制冷, 3=制热, 5=除湿, 6=自动, 255=默认', 'parse_mode': '枚举映射', 'enum_mappings': [{'value': 0, 'label': '关'}, {'value': 1, 'label': '通风'}, {'value': 2, 'label': '制冷'}, {'value': 3, 'label': '制热'}, {'value': 5, 'label': '除湿'}, {'value': 6, 'label': '自动'}, {'value': 255, 'label': '默认'}]},
            {'name': '设置温度', 'hex_value': '00C8', 'byte_count': 2, 'field_type': '数据', 'description': '[-99°C,99°C] 精度0.1°C'},
            {'name': '当前温度', 'hex_value': '00C8', 'byte_count': 2, 'field_type': '数据', 'description': '[-99°C,99°C] 精度0.1°C'},
            {'name': '当前湿度', 'hex_value': '0032', 'byte_count': 2, 'field_type': '数据', 'description': '[0%,100%] 精度0.1%'},
            {'name': '预留1', 'hex_value': '00', 'byte_count': 1, 'field_type': '数据', 'description': '预留'},
            {'name': '预留2', 'hex_value': '00', 'byte_count': 1, 'field_type': '数据', 'description': '预留'},
            {'name': '预留3', 'hex_value': '00', 'byte_count': 1, 'field_type': '数据', 'description': '预留'},
            {'name': 'CRC16', 'hex_value': '', 'byte_count': 2, 'field_type': '校验', 'description': 'CRC16校验(高位在前)', 'checksum_algorithm': 'CRC16/MODBUS', 'checksum_start': 0, 'checksum_end': 17, 'checksum_byte_order': 'big'},
        ],
        'desc': 'GRMS查询空调(回复)',
    },
    # ===== 1.10 查询房务 (0x13/0x14) =====
    '查询房务(发送)': {
        'fields': [
            {'name': 'Header', 'hex_value': 'BA', 'byte_count': 1, 'field_type': '固定值', 'description': '命令头'},
            {'name': 'Func', 'hex_value': '13', 'byte_count': 1, 'field_type': '数据', 'description': '功能码 0x13'},
            {'name': 'Sequence', 'hex_value': '0001', 'byte_count': 2, 'field_type': '数据', 'description': '流水号'},
            {'name': 'Box', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备地址'},
            {'name': 'TotalLen', 'hex_value': '', 'byte_count': 2, 'field_type': '长度', 'description': '命令长度之和', 'length_start': 0, 'length_end': 3, 'length_byte_order': 'big'},
            {'name': 'DeviceCode', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备编码'},
            {'name': 'DeviceBox', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备地址'},
            {'name': 'CRC16', 'hex_value': '', 'byte_count': 2, 'field_type': '校验', 'description': 'CRC16校验(高位在前)', 'checksum_algorithm': 'CRC16/MODBUS', 'checksum_start': 0, 'checksum_end': 6, 'checksum_byte_order': 'big'},
        ],
        'desc': 'GRMS查询房务(发送)',
    },
    '查询房务(回复)': {
        'fields': [
            {'name': 'Header', 'hex_value': 'BA', 'byte_count': 1, 'field_type': '固定值', 'description': '命令头'},
            {'name': 'Func', 'hex_value': '14', 'byte_count': 1, 'field_type': '数据', 'description': '功能码 0x14'},
            {'name': 'Sequence', 'hex_value': '0001', 'byte_count': 2, 'field_type': '数据', 'description': '流水号'},
            {'name': 'Box', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备地址'},
            {'name': 'TotalLen', 'hex_value': '', 'byte_count': 2, 'field_type': '长度', 'description': '命令长度之和', 'length_start': 0, 'length_end': 3, 'length_byte_order': 'big'},
            {'name': 'DeviceCode', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备编码'},
            {'name': 'DeviceBox', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备地址'},
            {'name': 'ResponseDataLen', 'hex_value': '0015', 'byte_count': 2, 'field_type': '数据', 'description': '应答数据长度'},
            {'name': '身份卡类型', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '00=无人,01=客人卡,02=工程师卡,03=清洁卡,04=楼层卡,05=楼号卡,06=总控卡,07=应急卡,08=领班卡', 'parse_mode': '枚举映射', 'enum_mappings': [{'value': 0, 'label': '无人'}, {'value': 1, 'label': '客人卡'}, {'value': 2, 'label': '工程师卡'}, {'value': 3, 'label': '清洁卡'}, {'value': 4, 'label': '楼层卡'}, {'value': 5, 'label': '楼号卡'}, {'value': 6, 'label': '总控卡'}, {'value': 7, 'label': '应急卡'}, {'value': 8, 'label': '领班卡'}]},
            {'name': '求救', 'hex_value': '00', 'byte_count': 1, 'field_type': '数据', 'description': '1=存在, 0=不存在', 'parse_mode': '枚举映射', 'enum_mappings': [{'value': 0, 'label': '不存在'}, {'value': 1, 'label': '存在'}]},
            {'name': '服务', 'hex_value': '00', 'byte_count': 1, 'field_type': '数据', 'description': '1=存在, 0=不存在', 'parse_mode': '枚举映射', 'enum_mappings': [{'value': 0, 'label': '不存在'}, {'value': 1, 'label': '存在'}]},
            {'name': '勿扰', 'hex_value': '00', 'byte_count': 1, 'field_type': '数据', 'description': '1=存在, 0=不存在', 'parse_mode': '枚举映射', 'enum_mappings': [{'value': 0, 'label': '不存在'}, {'value': 1, 'label': '存在'}]},
            {'name': '稍后', 'hex_value': '00', 'byte_count': 1, 'field_type': '数据', 'description': '1=存在, 0=不存在', 'parse_mode': '枚举映射', 'enum_mappings': [{'value': 0, 'label': '不存在'}, {'value': 1, 'label': '存在'}]},
            {'name': '清扫', 'hex_value': '00', 'byte_count': 1, 'field_type': '数据', 'description': '1=存在, 0=不存在', 'parse_mode': '枚举映射', 'enum_mappings': [{'value': 0, 'label': '不存在'}, {'value': 1, 'label': '存在'}]},
            {'name': '洗衣', 'hex_value': '00', 'byte_count': 1, 'field_type': '数据', 'description': '1=存在, 0=不存在', 'parse_mode': '枚举映射', 'enum_mappings': [{'value': 0, 'label': '不存在'}, {'value': 1, 'label': '存在'}]},
            {'name': '门磁', 'hex_value': '00', 'byte_count': 1, 'field_type': '数据', 'description': '1=存在, 0=不存在', 'parse_mode': '枚举映射', 'enum_mappings': [{'value': 0, 'label': '不存在'}, {'value': 1, 'label': '存在'}]},
            {'name': '窗磁', 'hex_value': '00', 'byte_count': 1, 'field_type': '数据', 'description': '1=存在, 0=不存在', 'parse_mode': '枚举映射', 'enum_mappings': [{'value': 0, 'label': '不存在'}, {'value': 1, 'label': '存在'}]},
            {'name': '灯亮', 'hex_value': '00', 'byte_count': 1, 'field_type': '数据', 'description': '1=存在, 0=不存在', 'parse_mode': '枚举映射', 'enum_mappings': [{'value': 0, 'label': '不存在'}, {'value': 1, 'label': '存在'}]},
            {'name': '叫餐', 'hex_value': '00', 'byte_count': 1, 'field_type': '数据', 'description': '1=存在, 0=不存在', 'parse_mode': '枚举映射', 'enum_mappings': [{'value': 0, 'label': '不存在'}, {'value': 1, 'label': '存在'}]},
            {'name': '衣帽间探头报警', 'hex_value': '00', 'byte_count': 1, 'field_type': '数据', 'description': '1=报警, 0=取消', 'parse_mode': '枚举映射', 'enum_mappings': [{'value': 0, 'label': '取消'}, {'value': 1, 'label': '报警'}]},
            {'name': '衣帽间门磁报警', 'hex_value': '00', 'byte_count': 1, 'field_type': '数据', 'description': '1=报警, 0=取消', 'parse_mode': '枚举映射', 'enum_mappings': [{'value': 0, 'label': '取消'}, {'value': 1, 'label': '报警'}]},
            {'name': '房间探头报警', 'hex_value': '00', 'byte_count': 1, 'field_type': '数据', 'description': '1=报警, 0=取消', 'parse_mode': '枚举映射', 'enum_mappings': [{'value': 0, 'label': '取消'}, {'value': 1, 'label': '报警'}]},
            {'name': '卫生间探头报警', 'hex_value': '00', 'byte_count': 1, 'field_type': '数据', 'description': '1=报警, 0=取消', 'parse_mode': '枚举映射', 'enum_mappings': [{'value': 0, 'label': '取消'}, {'value': 1, 'label': '报警'}]},
            {'name': '房间门磁报警', 'hex_value': '00', 'byte_count': 1, 'field_type': '数据', 'description': '1=报警, 0=取消', 'parse_mode': '枚举映射', 'enum_mappings': [{'value': 0, 'label': '取消'}, {'value': 1, 'label': '报警'}]},
            {'name': '保险箱报警', 'hex_value': '00', 'byte_count': 1, 'field_type': '数据', 'description': '1=报警, 0=取消', 'parse_mode': '枚举映射', 'enum_mappings': [{'value': 0, 'label': '取消'}, {'value': 1, 'label': '报警'}]},
            {'name': '房间窗磁报警', 'hex_value': '00', 'byte_count': 1, 'field_type': '数据', 'description': '1=报警, 0=取消', 'parse_mode': '枚举映射', 'enum_mappings': [{'value': 0, 'label': '取消'}, {'value': 1, 'label': '报警'}]},
            {'name': '预留1', 'hex_value': '00', 'byte_count': 1, 'field_type': '数据', 'description': '预留'},
            {'name': '预留2', 'hex_value': '00', 'byte_count': 1, 'field_type': '数据', 'description': '预留'},
            {'name': '预留3', 'hex_value': '00', 'byte_count': 1, 'field_type': '数据', 'description': '预留'},
            {'name': 'CRC16', 'hex_value': '', 'byte_count': 2, 'field_type': '校验', 'description': 'CRC16校验(高位在前)', 'checksum_algorithm': 'CRC16/MODBUS', 'checksum_start': 0, 'checksum_end': 28, 'checksum_byte_order': 'big'},
        ],
        'desc': 'GRMS查询房务(回复)',
    },
    # ===== 1.11 查询房态 (0x15/0x16) =====
    '查询房态(发送)': {
        'fields': [
            {'name': 'Header', 'hex_value': 'BA', 'byte_count': 1, 'field_type': '固定值', 'description': '命令头'},
            {'name': 'Func', 'hex_value': '15', 'byte_count': 1, 'field_type': '数据', 'description': '功能码 0x15'},
            {'name': 'Sequence', 'hex_value': '0001', 'byte_count': 2, 'field_type': '数据', 'description': '流水号'},
            {'name': 'Box', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备地址'},
            {'name': 'TotalLen', 'hex_value': '', 'byte_count': 2, 'field_type': '长度', 'description': '命令长度之和', 'length_start': 0, 'length_end': 3, 'length_byte_order': 'big'},
            {'name': 'DeviceCode', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备编码'},
            {'name': 'DeviceBox', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备地址'},
            {'name': 'CRC16', 'hex_value': '', 'byte_count': 2, 'field_type': '校验', 'description': 'CRC16校验(高位在前)', 'checksum_algorithm': 'CRC16/MODBUS', 'checksum_start': 0, 'checksum_end': 6, 'checksum_byte_order': 'big'},
        ],
        'desc': 'GRMS查询房态(发送)',
    },
    '查询房态(回复)': {
        'fields': [
            {'name': 'Header', 'hex_value': 'BA', 'byte_count': 1, 'field_type': '固定值', 'description': '命令头'},
            {'name': 'Func', 'hex_value': '16', 'byte_count': 1, 'field_type': '数据', 'description': '功能码 0x16'},
            {'name': 'Sequence', 'hex_value': '0001', 'byte_count': 2, 'field_type': '数据', 'description': '流水号'},
            {'name': 'Box', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备地址'},
            {'name': 'TotalLen', 'hex_value': '', 'byte_count': 2, 'field_type': '长度', 'description': '命令长度之和', 'length_start': 0, 'length_end': 3, 'length_byte_order': 'big'},
            {'name': 'DeviceCode', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备编码'},
            {'name': 'DeviceBox', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备地址'},
            {'name': 'State', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '0=待租, 1=已租, 2=预定', 'parse_mode': '枚举映射', 'enum_mappings': [{'value': 0, 'label': '待租'}, {'value': 1, 'label': '已租'}, {'value': 2, 'label': '预定'}]},
            {'name': 'CRC16', 'hex_value': '', 'byte_count': 2, 'field_type': '校验', 'description': 'CRC16校验(高位在前)', 'checksum_algorithm': 'CRC16/MODBUS', 'checksum_start': 0, 'checksum_end': 7, 'checksum_byte_order': 'big'},
        ],
        'desc': 'GRMS查询房态(回复)',
    },
    # ===== 1.12 查询通道 (0x17/0x18) =====
    '查询通道(发送)': {
        'fields': [
            {'name': 'Header', 'hex_value': 'BA', 'byte_count': 1, 'field_type': '固定值', 'description': '命令头'},
            {'name': 'Func', 'hex_value': '17', 'byte_count': 1, 'field_type': '数据', 'description': '功能码 0x17'},
            {'name': 'Sequence', 'hex_value': '0001', 'byte_count': 2, 'field_type': '数据', 'description': '流水号'},
            {'name': 'Box', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备地址'},
            {'name': 'TotalLen', 'hex_value': '', 'byte_count': 2, 'field_type': '长度', 'description': '命令长度之和', 'length_start': 0, 'length_end': 3, 'length_byte_order': 'big'},
            {'name': 'DeviceCode', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备编码'},
            {'name': 'DeviceBox', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备地址'},
            {'name': 'QueryDataLen', 'hex_value': '0001', 'byte_count': 2, 'field_type': '数据', 'description': '查询数据长度'},
            {'name': '通道号', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '通道号 [1-255]'},
            {'name': 'CRC16', 'hex_value': '', 'byte_count': 2, 'field_type': '校验', 'description': 'CRC16校验(高位在前)', 'checksum_algorithm': 'CRC16/MODBUS', 'checksum_start': 0, 'checksum_end': 8, 'checksum_byte_order': 'big'},
        ],
        'desc': 'GRMS查询通道(发送)',
    },
    '查询通道(回复)': {
        'fields': [
            {'name': 'Header', 'hex_value': 'BA', 'byte_count': 1, 'field_type': '固定值', 'description': '命令头'},
            {'name': 'Func', 'hex_value': '18', 'byte_count': 1, 'field_type': '数据', 'description': '功能码 0x18'},
            {'name': 'Sequence', 'hex_value': '0001', 'byte_count': 2, 'field_type': '数据', 'description': '流水号'},
            {'name': 'Box', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备地址'},
            {'name': 'TotalLen', 'hex_value': '', 'byte_count': 2, 'field_type': '长度', 'description': '命令长度之和', 'length_start': 0, 'length_end': 3, 'length_byte_order': 'big'},
            {'name': 'DeviceCode', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备编码'},
            {'name': 'DeviceBox', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备地址'},
            {'name': 'ResponseDataLen', 'hex_value': '0008', 'byte_count': 2, 'field_type': '数据', 'description': '应答数据长度'},
            {'name': '通道号', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '通道号 [1-255]'},
            {'name': '通道类型', 'hex_value': '00', 'byte_count': 1, 'field_type': '数据', 'description': '0=开关, 1=调光, 2=LED', 'parse_mode': '枚举映射', 'enum_mappings': [{'value': 0, 'label': '开关'}, {'value': 1, 'label': '调光'}, {'value': 2, 'label': 'LED'}]},
            {'name': '亮度Level', 'hex_value': '64', 'byte_count': 1, 'field_type': '数据', 'description': '[0-100]'},
            {'name': '渐变时间', 'hex_value': '0064', 'byte_count': 2, 'field_type': '数据', 'description': '单位:毫秒'},
            {'name': '预留1', 'hex_value': '00', 'byte_count': 1, 'field_type': '数据', 'description': '预留'},
            {'name': '预留2', 'hex_value': '00', 'byte_count': 1, 'field_type': '数据', 'description': '预留'},
            {'name': '预留3', 'hex_value': '00', 'byte_count': 1, 'field_type': '数据', 'description': '预留'},
            {'name': 'CRC16', 'hex_value': '', 'byte_count': 2, 'field_type': '校验', 'description': 'CRC16校验(高位在前)', 'checksum_algorithm': 'CRC16/MODBUS', 'checksum_start': 0, 'checksum_end': 14, 'checksum_byte_order': 'big'},
        ],
        'desc': 'GRMS查询通道(回复)',
    },
    # ===== 1.13 查询窗帘 (0x19/0x1A) =====
    '查询窗帘(发送)': {
        'fields': [
            {'name': 'Header', 'hex_value': 'BA', 'byte_count': 1, 'field_type': '固定值', 'description': '命令头'},
            {'name': 'Func', 'hex_value': '19', 'byte_count': 1, 'field_type': '数据', 'description': '功能码 0x19'},
            {'name': 'Sequence', 'hex_value': '0001', 'byte_count': 2, 'field_type': '数据', 'description': '流水号'},
            {'name': 'Box', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备地址'},
            {'name': 'TotalLen', 'hex_value': '', 'byte_count': 2, 'field_type': '长度', 'description': '命令长度之和', 'length_start': 0, 'length_end': 3, 'length_byte_order': 'big'},
            {'name': 'DeviceCode', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备编码'},
            {'name': 'DeviceBox', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备地址'},
            {'name': 'QueryDataLen', 'hex_value': '0001', 'byte_count': 2, 'field_type': '数据', 'description': '查询数据长度'},
            {'name': '窗帘编号', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '窗帘编号 [1-255]'},
            {'name': 'CRC16', 'hex_value': '', 'byte_count': 2, 'field_type': '校验', 'description': 'CRC16校验(高位在前)', 'checksum_algorithm': 'CRC16/MODBUS', 'checksum_start': 0, 'checksum_end': 8, 'checksum_byte_order': 'big'},
        ],
        'desc': 'GRMS查询窗帘(发送)',
    },
    '查询窗帘(回复)': {
        'fields': [
            {'name': 'Header', 'hex_value': 'BA', 'byte_count': 1, 'field_type': '固定值', 'description': '命令头'},
            {'name': 'Func', 'hex_value': '1A', 'byte_count': 1, 'field_type': '数据', 'description': '功能码 0x1A'},
            {'name': 'Sequence', 'hex_value': '0001', 'byte_count': 2, 'field_type': '数据', 'description': '流水号'},
            {'name': 'Box', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备地址'},
            {'name': 'TotalLen', 'hex_value': '', 'byte_count': 2, 'field_type': '长度', 'description': '命令长度之和', 'length_start': 0, 'length_end': 3, 'length_byte_order': 'big'},
            {'name': 'DeviceCode', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备编码'},
            {'name': 'DeviceBox', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备地址'},
            {'name': 'ResponseDataLen', 'hex_value': '0007', 'byte_count': 2, 'field_type': '数据', 'description': '应答数据长度'},
            {'name': '窗帘编号', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '窗帘编号 [1-255]'},
            {'name': '窗帘状态', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '0=关, 1=开, 2=停', 'parse_mode': '枚举映射', 'enum_mappings': [{'value': 0, 'label': '关'}, {'value': 1, 'label': '开'}, {'value': 2, 'label': '停'}]},
            {'name': '预留1', 'hex_value': '00', 'byte_count': 1, 'field_type': '数据', 'description': '预留'},
            {'name': '预留2', 'hex_value': '00', 'byte_count': 1, 'field_type': '数据', 'description': '预留'},
            {'name': '预留3', 'hex_value': '00', 'byte_count': 1, 'field_type': '数据', 'description': '预留'},
            {'name': '预留4', 'hex_value': '00', 'byte_count': 1, 'field_type': '数据', 'description': '预留'},
            {'name': '预留5', 'hex_value': '00', 'byte_count': 1, 'field_type': '数据', 'description': '预留'},
            {'name': 'CRC16', 'hex_value': '', 'byte_count': 2, 'field_type': '校验', 'description': 'CRC16校验(高位在前)', 'checksum_algorithm': 'CRC16/MODBUS', 'checksum_start': 0, 'checksum_end': 14, 'checksum_byte_order': 'big'},
        ],
        'desc': 'GRMS查询窗帘(回复)',
    },
    # ===== 1.14 查询日期时间 (0x1B/0x1C) =====
    '查询日期时间(发送)': {
        'fields': [
            {'name': 'Header', 'hex_value': 'BA', 'byte_count': 1, 'field_type': '固定值', 'description': '命令头'},
            {'name': 'Func', 'hex_value': '1B', 'byte_count': 1, 'field_type': '数据', 'description': '功能码 0x1B'},
            {'name': 'Sequence', 'hex_value': '0001', 'byte_count': 2, 'field_type': '数据', 'description': '流水号'},
            {'name': 'Box', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备地址'},
            {'name': 'TotalLen', 'hex_value': '', 'byte_count': 2, 'field_type': '长度', 'description': '命令长度之和', 'length_start': 0, 'length_end': 3, 'length_byte_order': 'big'},
            {'name': 'DeviceCode', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备编码'},
            {'name': 'DeviceBox', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备地址'},
            {'name': 'CRC16', 'hex_value': '', 'byte_count': 2, 'field_type': '校验', 'description': 'CRC16校验(高位在前)', 'checksum_algorithm': 'CRC16/MODBUS', 'checksum_start': 0, 'checksum_end': 6, 'checksum_byte_order': 'big'},
        ],
        'desc': 'GRMS查询日期时间(发送)',
    },
    '查询日期时间(回复)': {
        'fields': [
            {'name': 'Header', 'hex_value': 'BA', 'byte_count': 1, 'field_type': '固定值', 'description': '命令头'},
            {'name': 'Func', 'hex_value': '1C', 'byte_count': 1, 'field_type': '数据', 'description': '功能码 0x1C'},
            {'name': 'Sequence', 'hex_value': '0001', 'byte_count': 2, 'field_type': '数据', 'description': '流水号'},
            {'name': 'Box', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备地址'},
            {'name': 'TotalLen', 'hex_value': '', 'byte_count': 2, 'field_type': '长度', 'description': '命令长度之和', 'length_start': 0, 'length_end': 3, 'length_byte_order': 'big'},
            {'name': 'DeviceCode', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备编码'},
            {'name': 'DeviceBox', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备地址'},
            {'name': 'YEAR', 'hex_value': '19', 'byte_count': 1, 'field_type': '数据', 'description': '年低位(年高位默认20)'},
            {'name': 'MONTH', 'hex_value': '0A', 'byte_count': 1, 'field_type': '数据', 'description': '月'},
            {'name': 'DAY', 'hex_value': '0E', 'byte_count': 1, 'field_type': '数据', 'description': '日'},
            {'name': 'WEEK', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '星期 [1-7]'},
            {'name': 'HOUR', 'hex_value': '0E', 'byte_count': 1, 'field_type': '数据', 'description': '时'},
            {'name': 'MINUTE', 'hex_value': '2F', 'byte_count': 1, 'field_type': '数据', 'description': '分'},
            {'name': 'SECOND', 'hex_value': '13', 'byte_count': 1, 'field_type': '数据', 'description': '秒'},
            {'name': 'CRC16', 'hex_value': '', 'byte_count': 2, 'field_type': '校验', 'description': 'CRC16校验(高位在前)', 'checksum_algorithm': 'CRC16/MODBUS', 'checksum_start': 0, 'checksum_end': 13, 'checksum_byte_order': 'big'},
        ],
        'desc': 'GRMS查询日期时间(回复)',
    },
    # ===== 1.15 查询调试授权 (0x1D/0x1E) =====
    '查询调试授权(发送)': {
        'fields': [
            {'name': 'Header', 'hex_value': 'BA', 'byte_count': 1, 'field_type': '固定值', 'description': '命令头'},
            {'name': 'Func', 'hex_value': '1D', 'byte_count': 1, 'field_type': '数据', 'description': '功能码 0x1D'},
            {'name': 'Sequence', 'hex_value': '0001', 'byte_count': 2, 'field_type': '数据', 'description': '流水号'},
            {'name': 'Box', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备地址'},
            {'name': 'TotalLen', 'hex_value': '', 'byte_count': 2, 'field_type': '长度', 'description': '命令长度之和', 'length_start': 0, 'length_end': 3, 'length_byte_order': 'big'},
            {'name': 'DeviceCode', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备编码'},
            {'name': 'DeviceBox', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备地址'},
            {'name': 'CRC16', 'hex_value': '', 'byte_count': 2, 'field_type': '校验', 'description': 'CRC16校验(高位在前)', 'checksum_algorithm': 'CRC16/MODBUS', 'checksum_start': 0, 'checksum_end': 6, 'checksum_byte_order': 'big'},
        ],
        'desc': 'GRMS查询调试授权(发送)',
    },
    '查询调试授权(回复)': {
        'fields': [
            {'name': 'Header', 'hex_value': 'BA', 'byte_count': 1, 'field_type': '固定值', 'description': '命令头'},
            {'name': 'Func', 'hex_value': '1E', 'byte_count': 1, 'field_type': '数据', 'description': '功能码 0x1E'},
            {'name': 'Sequence', 'hex_value': '0001', 'byte_count': 2, 'field_type': '数据', 'description': '流水号'},
            {'name': 'Box', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备地址'},
            {'name': 'TotalLen', 'hex_value': '', 'byte_count': 2, 'field_type': '长度', 'description': '命令长度之和', 'length_start': 0, 'length_end': 3, 'length_byte_order': 'big'},
            {'name': 'DeviceCode', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备编码'},
            {'name': 'DeviceBox', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备地址'},
            {'name': 'AuthStatus', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '0=未授权, 1=已授权', 'parse_mode': '枚举映射', 'enum_mappings': [{'value': 0, 'label': '未授权'}, {'value': 1, 'label': '已授权'}]},
            {'name': 'CRC16', 'hex_value': '', 'byte_count': 2, 'field_type': '校验', 'description': 'CRC16校验(高位在前)', 'checksum_algorithm': 'CRC16/MODBUS', 'checksum_start': 0, 'checksum_end': 7, 'checksum_byte_order': 'big'},
        ],
        'desc': 'GRMS查询调试授权(回复)',
    },
}
