"""GRMS 监控协议 - 数据上报类命令 (0x21-0x2E)
空调数据上报、房务数据上报、通道数据上报、窗帘数据上报、环境数据上报
"""

GRMS_DATA_TEMPLATES = {
    # ===== 1.16 空调数据上报 (0x21/0x22) =====
    '空调数据上报(发送)': {
        'fields': [
            {'name': 'Header', 'hex_value': 'BA', 'byte_count': 1, 'field_type': '固定值', 'description': '命令头'},
            {'name': 'Func', 'hex_value': '21', 'byte_count': 1, 'field_type': '数据', 'description': '功能码 0x21'},
            {'name': 'Sequence', 'hex_value': '0001', 'byte_count': 2, 'field_type': '数据', 'description': '流水号'},
            {'name': 'Box', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备地址'},
            {'name': 'TotalLen', 'hex_value': '', 'byte_count': 2, 'field_type': '长度', 'description': '命令长度之和', 'length_start': 0, 'length_end': 3, 'length_byte_order': 'big'},
            {'name': 'DeviceCode', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备编码'},
            {'name': 'DeviceBox', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备地址'},
            {'name': 'DataLen', 'hex_value': '000D', 'byte_count': 2, 'field_type': '数据', 'description': '数据长度'},
            {'name': '空调ID', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '空调ID [1-255]'},
            {'name': '开关', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '0=关, 1=开, 255=默认', 'parse_mode': '枚举映射', 'enum_mappings': [{'value': 0, 'label': '关'}, {'value': 1, 'label': '开'}, {'value': 255, 'label': '默认'}]},
            {'name': '风速', 'hex_value': '64', 'byte_count': 1, 'field_type': '数据', 'description': '0=关, 1-100=档位, 104=自动, 255=默认'},
            {'name': '模式', 'hex_value': '02', 'byte_count': 1, 'field_type': '数据', 'description': '0=关, 1=通风, 2=制冷, 3=制热, 5=除湿, 6=自动, 255=默认', 'parse_mode': '枚举映射', 'enum_mappings': [{'value': 0, 'label': '关'}, {'value': 1, 'label': '通风'}, {'value': 2, 'label': '制冷'}, {'value': 3, 'label': '制热'}, {'value': 5, 'label': '除湿'}, {'value': 6, 'label': '自动'}, {'value': 255, 'label': '默认'}]},
            {'name': '设置温度', 'hex_value': '00C8', 'byte_count': 2, 'field_type': '数据', 'description': '[-99°C,99°C] 精度0.1°C'},
            {'name': '当前温度', 'hex_value': '00C8', 'byte_count': 2, 'field_type': '数据', 'description': '[-99°C,99°C] 精度0.1°C'},
            {'name': '当前湿度', 'hex_value': '0032', 'byte_count': 2, 'field_type': '数据', 'description': '[0%,100%] 精度0.1%'},
            {'name': '预留1', 'hex_value': '00', 'byte_count': 1, 'field_type': '数据', 'description': '预留'},
            {'name': '预留2', 'hex_value': '00', 'byte_count': 1, 'field_type': '数据', 'description': '预留'},
            {'name': '预留3', 'hex_value': '00', 'byte_count': 1, 'field_type': '数据', 'description': '预留'},
            {'name': 'CRC16', 'hex_value': '', 'byte_count': 2, 'field_type': '校验', 'description': 'CRC16校验(高位在前)', 'checksum_algorithm': 'CRC16/MODBUS', 'checksum_start': 0, 'checksum_end': 17, 'checksum_byte_order': 'big'},
        ],
        'desc': 'GRMS空调数据上报(发送)',
    },
    '空调数据上报(回复)': {
        'fields': [
            {'name': 'Header', 'hex_value': 'BA', 'byte_count': 1, 'field_type': '固定值', 'description': '命令头'},
            {'name': 'Func', 'hex_value': '22', 'byte_count': 1, 'field_type': '数据', 'description': '功能码 0x22'},
            {'name': 'Sequence', 'hex_value': '0001', 'byte_count': 2, 'field_type': '数据', 'description': '流水号'},
            {'name': 'Box', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备地址'},
            {'name': 'TotalLen', 'hex_value': '', 'byte_count': 2, 'field_type': '长度', 'description': '命令长度之和', 'length_start': 0, 'length_end': 3, 'length_byte_order': 'big'},
            {'name': 'DeviceCode', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备编码'},
            {'name': 'DeviceBox', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备地址'},
            {'name': 'Result', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '0=失败, 1=成功', 'parse_mode': '枚举映射', 'enum_mappings': [{'value': 0, 'label': '失败'}, {'value': 1, 'label': '成功'}]},
            {'name': 'CRC16', 'hex_value': '', 'byte_count': 2, 'field_type': '校验', 'description': 'CRC16校验(高位在前)', 'checksum_algorithm': 'CRC16/MODBUS', 'checksum_start': 0, 'checksum_end': 7, 'checksum_byte_order': 'big'},
        ],
        'desc': 'GRMS空调数据上报(回复)',
    },
    # ===== 1.17 房务数据上报 (0x23/0x24) =====
    '房务数据上报(发送)': {
        'fields': [
            {'name': 'Header', 'hex_value': 'BA', 'byte_count': 1, 'field_type': '固定值', 'description': '命令头'},
            {'name': 'Func', 'hex_value': '23', 'byte_count': 1, 'field_type': '数据', 'description': '功能码 0x23'},
            {'name': 'Sequence', 'hex_value': '0001', 'byte_count': 2, 'field_type': '数据', 'description': '流水号'},
            {'name': 'Box', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备地址'},
            {'name': 'TotalLen', 'hex_value': '', 'byte_count': 2, 'field_type': '长度', 'description': '命令长度之和', 'length_start': 0, 'length_end': 3, 'length_byte_order': 'big'},
            {'name': 'DeviceCode', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备编码'},
            {'name': 'DeviceBox', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备地址'},
            {'name': 'DataLen', 'hex_value': '0015', 'byte_count': 2, 'field_type': '数据', 'description': '数据长度'},
            {'name': '身份卡类型', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '00=无人,01=客人卡,02=工程师卡,03=清洁卡,04=楼层卡,05=楼号卡,06=总控卡,07=应急卡,08=领班卡', 'parse_mode': '枚举映射', 'enum_mappings': [{'value': 0, 'label': '无人'}, {'value': 1, 'label': '客人卡'}, {'value': 2, 'label': '工程师卡'}, {'value': 3, 'label': '清洁卡'}, {'value': 4, 'label': '楼层卡'}, {'value': 5, 'label': '楼号卡'}, {'value': 6, 'label': '总控卡'}, {'value': 7, 'label': '应急卡'}, {'value': 8, 'label': '领班卡'}]},
            {'name': '求救', 'hex_value': '00', 'byte_count': 1, 'field_type': '数据', 'description': '1=存在, 0=不存在', 'parse_mode': '枚举映射', 'enum_mappings': [{'value': 0, 'label': '不存在'}, {'value': 1, 'label': '存在'}]},
            {'name': '服务', 'hex_value': '00', 'byte_count': 1, 'field_type': '数据', 'description': '1=存在, 0=不存在', 'parse_mode': '枚举映射', 'enum_mappings': [{'value': 0, 'label': '不存在'}, {'value': 1, 'label': '存在'}]},
            {'name': '勿扰', 'hex_value': '00', 'byte_count': 1, 'field_type': '数据', 'description': '1=存在, 0=不存在', 'parse_mode': '枚举映射', 'enum_mappings': [{'value': 0, 'label': '不存在'}, {'value': 1, 'label': '存在'}]},
            {'name': '稍后', 'hex_value': '00', 'byte_count': 1, 'field_type': '数据', 'description': '1=存在, 0=不存在', 'parse_mode': '枚举映射', 'enum_mappings': [{'value': 0, 'label': '不存在'}, {'value': 1, 'label': '存在'}]},
            {'name': '清扫', 'hex_value': '00', 'byte_count': 1, 'field_type': '数据', 'description': '1=存在, 0=不存在', 'parse_mode': '枚举映射', 'enum_mappings': [{'value': 0, 'label': '不存在'}, {'value': 1, 'label': '存在'}]},
            {'name': '洗衣', 'hex_value': '00', 'byte_count': 1, 'field_type': '数据', 'description': '1=存在, 0=不存在', 'parse_mode': '枚举映射', 'enum_mappings': [{'value': 0, 'label': '不存在'}, {'value': 1, 'label': '存在'}]},
            {'name': '门磁', 'hex_value': '00', 'byte_count': 1, 'field_type': '数据', 'description': '1=存在, 0=不存在', 'parse_mode': '枚举映射', 'enum_mappings': [{'value': 0, 'label': '不存在'}, {'value': 1, 'label': '存在'}]},
            {'name': '窗磁', 'hex_value': '00', 'byte_count': 1, 'field_type': '数据', 'description': '1=存在, 0=不存在', 'parse_mode': '枚举映射', 'enum_mappings': [{'value': 0, 'label': '不存在'}, {'value': 1, 'label': '存在'}]},
            {'name': '灯亮', 'hex_value': '00', 'byte_count': 1, 'field_type': '数据', 'description': '1=存在, 0=不存在', 'parse_mode': '枚举映射', 'enum_mappings': [{'value': 0, 'label': '不存在'}, {'value': 1, 'label': '存在'}]},
            {'name': '叫餐', 'hex_value': '00', 'byte_count': 1, 'field_type': '数据', 'description': '1=存在, 0=不存在', 'parse_mode': '枚举映射', 'enum_mappings': [{'value': 0, 'label': '不存在'}, {'value': 1, 'label': '存在'}]},
            {'name': '衣帽间探头报警', 'hex_value': '00', 'byte_count': 1, 'field_type': '数据', 'description': '1=报警, 0=取消', 'parse_mode': '枚举映射', 'enum_mappings': [{'value': 0, 'label': '取消'}, {'value': 1, 'label': '报警'}]},
            {'name': '衣帽间门磁报警', 'hex_value': '00', 'byte_count': 1, 'field_type': '数据', 'description': '1=报警, 0=取消', 'parse_mode': '枚举映射', 'enum_mappings': [{'value': 0, 'label': '取消'}, {'value': 1, 'label': '报警'}]},
            {'name': '房间探头报警', 'hex_value': '00', 'byte_count': 1, 'field_type': '数据', 'description': '1=报警, 0=取消', 'parse_mode': '枚举映射', 'enum_mappings': [{'value': 0, 'label': '取消'}, {'value': 1, 'label': '报警'}]},
            {'name': '卫生间探头报警', 'hex_value': '00', 'byte_count': 1, 'field_type': '数据', 'description': '1=报警, 0=取消', 'parse_mode': '枚举映射', 'enum_mappings': [{'value': 0, 'label': '取消'}, {'value': 1, 'label': '报警'}]},
            {'name': '房间门磁报警', 'hex_value': '00', 'byte_count': 1, 'field_type': '数据', 'description': '1=报警, 0=取消', 'parse_mode': '枚举映射', 'enum_mappings': [{'value': 0, 'label': '取消'}, {'value': 1, 'label': '报警'}]},
            {'name': '保险箱报警', 'hex_value': '00', 'byte_count': 1, 'field_type': '数据', 'description': '1=报警, 0=取消', 'parse_mode': '枚举映射', 'enum_mappings': [{'value': 0, 'label': '取消'}, {'value': 1, 'label': '报警'}]},
            {'name': '房间窗磁报警', 'hex_value': '00', 'byte_count': 1, 'field_type': '数据', 'description': '1=报警, 0=取消', 'parse_mode': '枚举映射', 'enum_mappings': [{'value': 0, 'label': '取消'}, {'value': 1, 'label': '报警'}]},
            {'name': '预留1', 'hex_value': '00', 'byte_count': 1, 'field_type': '数据', 'description': '预留'},
            {'name': '预留2', 'hex_value': '00', 'byte_count': 1, 'field_type': '数据', 'description': '预留'},
            {'name': '预留3', 'hex_value': '00', 'byte_count': 1, 'field_type': '数据', 'description': '预留'},
            {'name': 'CRC16', 'hex_value': '', 'byte_count': 2, 'field_type': '校验', 'description': 'CRC16校验(高位在前)', 'checksum_algorithm': 'CRC16/MODBUS', 'checksum_start': 0, 'checksum_end': 28, 'checksum_byte_order': 'big'},
        ],
        'desc': 'GRMS房务数据上报(发送)',
    },
    '房务数据上报(回复)': {
        'fields': [
            {'name': 'Header', 'hex_value': 'BA', 'byte_count': 1, 'field_type': '固定值', 'description': '命令头'},
            {'name': 'Func', 'hex_value': '24', 'byte_count': 1, 'field_type': '数据', 'description': '功能码 0x24'},
            {'name': 'Sequence', 'hex_value': '0001', 'byte_count': 2, 'field_type': '数据', 'description': '流水号'},
            {'name': 'Box', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备地址'},
            {'name': 'TotalLen', 'hex_value': '', 'byte_count': 2, 'field_type': '长度', 'description': '命令长度之和', 'length_start': 0, 'length_end': 3, 'length_byte_order': 'big'},
            {'name': 'DeviceCode', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备编码'},
            {'name': 'DeviceBox', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备地址'},
            {'name': 'Result', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '0=失败, 1=成功', 'parse_mode': '枚举映射', 'enum_mappings': [{'value': 0, 'label': '失败'}, {'value': 1, 'label': '成功'}]},
            {'name': 'CRC16', 'hex_value': '', 'byte_count': 2, 'field_type': '校验', 'description': 'CRC16校验(高位在前)', 'checksum_algorithm': 'CRC16/MODBUS', 'checksum_start': 0, 'checksum_end': 7, 'checksum_byte_order': 'big'},
        ],
        'desc': 'GRMS房务数据上报(回复)',
    },
    # ===== 1.18 通道数据上报 (0x25/0x26) =====
    '通道数据上报(发送)': {
        'fields': [
            {'name': 'Header', 'hex_value': 'BA', 'byte_count': 1, 'field_type': '固定值', 'description': '命令头'},
            {'name': 'Func', 'hex_value': '25', 'byte_count': 1, 'field_type': '数据', 'description': '功能码 0x25'},
            {'name': 'Sequence', 'hex_value': '0001', 'byte_count': 2, 'field_type': '数据', 'description': '流水号'},
            {'name': 'Box', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备地址'},
            {'name': 'TotalLen', 'hex_value': '', 'byte_count': 2, 'field_type': '长度', 'description': '命令长度之和', 'length_start': 0, 'length_end': 3, 'length_byte_order': 'big'},
            {'name': 'DeviceCode', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备编码'},
            {'name': 'DeviceBox', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备地址'},
            {'name': 'DataLen', 'hex_value': '0008', 'byte_count': 2, 'field_type': '数据', 'description': '数据长度'},
            {'name': '通道号', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '通道号 [1-255]'},
            {'name': '通道类型', 'hex_value': '00', 'byte_count': 1, 'field_type': '数据', 'description': '0=开关, 1=调光, 2=LED', 'parse_mode': '枚举映射', 'enum_mappings': [{'value': 0, 'label': '开关'}, {'value': 1, 'label': '调光'}, {'value': 2, 'label': 'LED'}]},
            {'name': '亮度Level', 'hex_value': '64', 'byte_count': 1, 'field_type': '数据', 'description': '[0-100]'},
            {'name': '渐变时间', 'hex_value': '0064', 'byte_count': 2, 'field_type': '数据', 'description': '单位:毫秒'},
            {'name': '预留1', 'hex_value': '00', 'byte_count': 1, 'field_type': '数据', 'description': '预留'},
            {'name': '预留2', 'hex_value': '00', 'byte_count': 1, 'field_type': '数据', 'description': '预留'},
            {'name': '预留3', 'hex_value': '00', 'byte_count': 1, 'field_type': '数据', 'description': '预留'},
            {'name': 'CRC16', 'hex_value': '', 'byte_count': 2, 'field_type': '校验', 'description': 'CRC16校验(高位在前)', 'checksum_algorithm': 'CRC16/MODBUS', 'checksum_start': 0, 'checksum_end': 14, 'checksum_byte_order': 'big'},
        ],
        'desc': 'GRMS通道数据上报(发送)',
    },
    '通道数据上报(回复)': {
        'fields': [
            {'name': 'Header', 'hex_value': 'BA', 'byte_count': 1, 'field_type': '固定值', 'description': '命令头'},
            {'name': 'Func', 'hex_value': '26', 'byte_count': 1, 'field_type': '数据', 'description': '功能码 0x26'},
            {'name': 'Sequence', 'hex_value': '0001', 'byte_count': 2, 'field_type': '数据', 'description': '流水号'},
            {'name': 'Box', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备地址'},
            {'name': 'TotalLen', 'hex_value': '', 'byte_count': 2, 'field_type': '长度', 'description': '命令长度之和', 'length_start': 0, 'length_end': 3, 'length_byte_order': 'big'},
            {'name': 'DeviceCode', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备编码'},
            {'name': 'DeviceBox', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备地址'},
            {'name': 'Result', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '0=失败, 1=成功', 'parse_mode': '枚举映射', 'enum_mappings': [{'value': 0, 'label': '失败'}, {'value': 1, 'label': '成功'}]},
            {'name': 'CRC16', 'hex_value': '', 'byte_count': 2, 'field_type': '校验', 'description': 'CRC16校验(高位在前)', 'checksum_algorithm': 'CRC16/MODBUS', 'checksum_start': 0, 'checksum_end': 7, 'checksum_byte_order': 'big'},
        ],
        'desc': 'GRMS通道数据上报(回复)',
    },
    # ===== 1.19 窗帘数据上报 (0x27/0x28) =====
    '窗帘数据上报(发送)': {
        'fields': [
            {'name': 'Header', 'hex_value': 'BA', 'byte_count': 1, 'field_type': '固定值', 'description': '命令头'},
            {'name': 'Func', 'hex_value': '27', 'byte_count': 1, 'field_type': '数据', 'description': '功能码 0x27'},
            {'name': 'Sequence', 'hex_value': '0001', 'byte_count': 2, 'field_type': '数据', 'description': '流水号'},
            {'name': 'Box', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备地址'},
            {'name': 'TotalLen', 'hex_value': '', 'byte_count': 2, 'field_type': '长度', 'description': '命令长度之和', 'length_start': 0, 'length_end': 3, 'length_byte_order': 'big'},
            {'name': 'DeviceCode', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备编码'},
            {'name': 'DeviceBox', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备地址'},
            {'name': 'DataLen', 'hex_value': '0007', 'byte_count': 2, 'field_type': '数据', 'description': '数据长度'},
            {'name': '窗帘编号', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '窗帘编号 [1-255]'},
            {'name': '窗帘状态', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '0=关, 1=开, 2=停', 'parse_mode': '枚举映射', 'enum_mappings': [{'value': 0, 'label': '关'}, {'value': 1, 'label': '开'}, {'value': 2, 'label': '停'}]},
            {'name': '预留1', 'hex_value': '00', 'byte_count': 1, 'field_type': '数据', 'description': '预留'},
            {'name': '预留2', 'hex_value': '00', 'byte_count': 1, 'field_type': '数据', 'description': '预留'},
            {'name': '预留3', 'hex_value': '00', 'byte_count': 1, 'field_type': '数据', 'description': '预留'},
            {'name': '预留4', 'hex_value': '00', 'byte_count': 1, 'field_type': '数据', 'description': '预留'},
            {'name': '预留5', 'hex_value': '00', 'byte_count': 1, 'field_type': '数据', 'description': '预留'},
            {'name': 'CRC16', 'hex_value': '', 'byte_count': 2, 'field_type': '校验', 'description': 'CRC16校验(高位在前)', 'checksum_algorithm': 'CRC16/MODBUS', 'checksum_start': 0, 'checksum_end': 14, 'checksum_byte_order': 'big'},
        ],
        'desc': 'GRMS窗帘数据上报(发送)',
    },
    '窗帘数据上报(回复)': {
        'fields': [
            {'name': 'Header', 'hex_value': 'BA', 'byte_count': 1, 'field_type': '固定值', 'description': '命令头'},
            {'name': 'Func', 'hex_value': '28', 'byte_count': 1, 'field_type': '数据', 'description': '功能码 0x28'},
            {'name': 'Sequence', 'hex_value': '0001', 'byte_count': 2, 'field_type': '数据', 'description': '流水号'},
            {'name': 'Box', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备地址'},
            {'name': 'TotalLen', 'hex_value': '', 'byte_count': 2, 'field_type': '长度', 'description': '命令长度之和', 'length_start': 0, 'length_end': 3, 'length_byte_order': 'big'},
            {'name': 'DeviceCode', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备编码'},
            {'name': 'DeviceBox', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备地址'},
            {'name': 'Result', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '0=失败, 1=成功', 'parse_mode': '枚举映射', 'enum_mappings': [{'value': 0, 'label': '失败'}, {'value': 1, 'label': '成功'}]},
            {'name': 'CRC16', 'hex_value': '', 'byte_count': 2, 'field_type': '校验', 'description': 'CRC16校验(高位在前)', 'checksum_algorithm': 'CRC16/MODBUS', 'checksum_start': 0, 'checksum_end': 7, 'checksum_byte_order': 'big'},
        ],
        'desc': 'GRMS窗帘数据上报(回复)',
    },
    # ===== 1.20 环境数据上报 (0x29/0x2A) =====
    '环境数据上报(发送)': {
        'fields': [
            {'name': 'Header', 'hex_value': 'BA', 'byte_count': 1, 'field_type': '固定值', 'description': '命令头'},
            {'name': 'Func', 'hex_value': '29', 'byte_count': 1, 'field_type': '数据', 'description': '功能码 0x29'},
            {'name': 'Sequence', 'hex_value': '0001', 'byte_count': 2, 'field_type': '数据', 'description': '流水号'},
            {'name': 'Box', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备地址'},
            {'name': 'TotalLen', 'hex_value': '', 'byte_count': 2, 'field_type': '长度', 'description': '命令长度之和', 'length_start': 0, 'length_end': 3, 'length_byte_order': 'big'},
            {'name': 'DeviceCode', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备编码'},
            {'name': 'DeviceBox', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备地址'},
            {'name': 'DataLen', 'hex_value': '0004', 'byte_count': 2, 'field_type': '数据', 'description': '数据长度'},
            {'name': '温度', 'hex_value': '00C8', 'byte_count': 2, 'field_type': '数据', 'description': '[-99°C,99°C] 精度0.1°C'},
            {'name': '湿度', 'hex_value': '0032', 'byte_count': 2, 'field_type': '数据', 'description': '[0%,100%] 精度0.1%'},
            {'name': 'CRC16', 'hex_value': '', 'byte_count': 2, 'field_type': '校验', 'description': 'CRC16校验(高位在前)', 'checksum_algorithm': 'CRC16/MODBUS', 'checksum_start': 0, 'checksum_end': 9, 'checksum_byte_order': 'big'},
        ],
        'desc': 'GRMS环境数据上报(发送)',
    },
    '环境数据上报(回复)': {
        'fields': [
            {'name': 'Header', 'hex_value': 'BA', 'byte_count': 1, 'field_type': '固定值', 'description': '命令头'},
            {'name': 'Func', 'hex_value': '2A', 'byte_count': 1, 'field_type': '数据', 'description': '功能码 0x2A'},
            {'name': 'Sequence', 'hex_value': '0001', 'byte_count': 2, 'field_type': '数据', 'description': '流水号'},
            {'name': 'Box', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备地址'},
            {'name': 'TotalLen', 'hex_value': '', 'byte_count': 2, 'field_type': '长度', 'description': '命令长度之和', 'length_start': 0, 'length_end': 3, 'length_byte_order': 'big'},
            {'name': 'DeviceCode', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备编码'},
            {'name': 'DeviceBox', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '设备地址'},
            {'name': 'Result', 'hex_value': '01', 'byte_count': 1, 'field_type': '数据', 'description': '0=失败, 1=成功', 'parse_mode': '枚举映射', 'enum_mappings': [{'value': 0, 'label': '失败'}, {'value': 1, 'label': '成功'}]},
            {'name': 'CRC16', 'hex_value': '', 'byte_count': 2, 'field_type': '校验', 'description': 'CRC16校验(高位在前)', 'checksum_algorithm': 'CRC16/MODBUS', 'checksum_start': 0, 'checksum_end': 7, 'checksum_byte_order': 'big'},
        ],
        'desc': 'GRMS环境数据上报(回复)',
    },
}
